### ISSUE TITLE
feat: release and move into ipld org

### ISSUE THREAD

**Issue by mikeal** [ipld/js-bitcoin#1]
I need to use this today and just realized it hasn’t been published yet :)

Should probably move it into the IPLD org as well since it’s going to be published into the @ipld namespace.

**Comment by rvagg** [comment]
moved, but this needs to get up to sync with current multiformats, that's where it got stalled, perhaps you can help with that because I still haven't got my head around the new esm stack and am unsure how much I should pull that in to libraries like this

**Comment by mikeal** [comment]
sure. for what it’s worth i have this working with the current multiformats in a small project, so I think it’s actually fine, but once i have the new build toolchain setup i can take on migrating this repo.
