### ISSUE TITLE
bug: allow `Buffer` as input

### ISSUE THREAD

**Issue by mikeal** [ipld/js-bitcoin#2]
I think you meant to do a check if your input types are Buffer **or** Uint8Array, but they actually **only** accepting Uint8Array because you’re checking the constructor name.

https://github.com/rvagg/js-bitcoin/blob/master/src/bitcoin-block.js#L17

If you want to only accept Uint8Array then we should just clean up the error messages. If you want to allow Buffer as input then just drop the constructor name check and just check if it’s an instanceof Uint8Array.

These checks are all over the place so instead of going through and fixing all of them I just changed my usage to convert to Uint8Array, so this isn’t block me or anything, just wanted to make sure it got logged.

**Comment by rvagg** [comment]
https://github.com/ipld/js-bitcoin/pull/3
